spring:
  application:
    name: TestWork
  threads:
    virtual:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    consumer:
      group-id: user-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#app:
#  kafka:
#    input-topic: VTB_topic_1
#    output-topic: VTB_topic_2
server:
  port: 12221
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
  observations:
    annotations:
      enabled: true
  metrics:
    tags:
      application: TestWork